"""Made changes to type column

Revision ID: 831f7c5809df
Revises: ffaa07f9e762
Create Date: 2024-05-20 23:27:35.468369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831f7c5809df'
down_revision = 'ffaa07f9e762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
