"""confirm Pass

Revision ID: dd309c0a7486
Revises: a3a98d1e6469
Create Date: 2024-05-23 17:07:05.807245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd309c0a7486'
down_revision = 'a3a98d1e6469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_password', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirm_password')

    # ### end Alembic commands ###
